name: 'Run Buddy Pipeline'
description: 'Runs Buddy CI/CD pipelines from GitHub Actions'
author: 'Marcel Gańczarczyk'
runs:
  using: 'node24'
  main: 'dist/index.js'
inputs:
  workspace:
    description: 'Buddy workspace domain'
    required: true
  project:
    description: 'Buddy project name (URL handle)'
    required: true
  identifier:
    description: 'Pipeline identifier (human-readable ID)'
    required: true
  comment:
    description: 'Run comment (e.g., commit hash, build info)'
    required: false
  wait:
    description: 'Wait for run to finish (minutes). If not provided, returns execution URL immediately.'
    required: false
  branch:
    description: 'Repository branch name'
    required: false
  tag:
    description: 'Repository tag name'
    required: false
  revision:
    description: 'Repository revision (commit SHA)'
    required: false
  pull-request:
    description: 'Repository pull request ID'
    required: false
  refresh:
    description: 'Deploy from scratch'
    required: false
  clear-cache:
    description: 'Clear cache before running the pipeline'
    required: false
  priority:
    description: 'Run priority (LOW, NORMAL, or HIGH). Default is NORMAL'
    required: false
  region:
    description: 'Override default region (EU or US)'
    required: false
  variable:
    description: 'Variables in key:value format (one per line or comma-separated)'
    required: false
  variable-masked:
    description: 'Masked variables in key:value format (one per line or comma-separated)'
    required: false
  schedule:
    description: 'Schedule execution time (e.g., 2016-11-18T12:38:16.000Z or 30s, 10m, 3h10m30s)'
    required: false
  action:
    description: 'Action ID(s) to run (one per line or comma-separated)'
    required: false
  api:
    description: 'Override API URL'
    required: false
outputs:
  run_url:
    description: 'The URL of the pipeline execution'
branding:
  icon: 'play'
  color: 'blue'
